config/routes.rb
Rails.application.routes.draw do

  # Orders
  get 'order_done', to: 'orders#done'
  get 'order_download', to: 'orders#order_download'

  # API
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'login', to: "authenticate#login"
      get 'orders', to: 'authenticate#orders'
      post 'orders', to: 'authenticate#order'
    end
  end

  # Staff Login system
  get "login", to: "staffs#login"
  post "validate", to: "staffs#validate"
  get "logout", to: "staffs#logout"
  get "dashboard", to: "orders#unsolve"

  resources :details
  resources :orders
  resources :products
  resources :staffs
  resources :departments
  resources :customers
  root "staffs#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :not_admin, except: [:login, :validate, :logout]
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  def login
    redirect_to orders_path if session[:staff] && session[:staff] != nil
  end

  def validate
		@staff = Staff.find_by(username: params[:username])
		if @staff && @staff.password == params[:password]
			session[:staff] = @staff.id
			session[:staff_username] = @staff.username
			redirect_to orders_path, notice: 'You have successfully logged in.'
		else
			redirect_to root_path, notice: 'Invalid login attempt.'
		end
  end

  def logout
    session.delete(:staff)
    session.delete(:staff_username)
    render 'login', notice: 'Successfully Logout'
  end

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:username, :password, :department_id)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(staff) do |f| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :department_id %>
    <%= f.text_field :department_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> | <%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table class="dt table table-striped table-bordered">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Department</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.username %></td>
        <td><%= staff.password %></td>
        <td><%= link_to staff.department.name, department_path(staff.department) %></td>
        <td><%= link_to 'Show', staff %>
        <%= link_to 'Edit', edit_staff_path(staff) %>
        <%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DawAye</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">

        <%= yield %>

        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
                <p id="notice"><%= flash[:notice] %></p>
          </div>
        <% end %>

        <%= form_tag('validate', method: :post) do  %>
          <div class="field form-group">
            <%= label_tag :username %><br>
            <%= text_field_tag(:username,nil, class: "form-control", autofocus: 'autofocus') %>
          </div>
          <div class="field form-group">
            <%= label :password, "Password" %><br>
            <%= password_field_tag(:password, nil, class: "form-control") %>
          </div>
          <div class="actions">
            <%= submit_tag("Login",class: "btn btn-primary") %> <%= link_to 'Back', root_path %>
          </div>
        <% end %>

    </div>
  </body>
</html>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @staff.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @staff.password %>
</p>

<p>
  <strong>Department:</strong>
  <%= @staff.department.name %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>