config/routes.rb
Rails.application.routes.draw do

  # Orders
  get 'order_done', to: 'orders#done'
  get 'order_download', to: 'orders#order_download'

  # API
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'login', to: "authenticate#login"
      get 'orders', to: 'authenticate#orders'
      post 'orders', to: 'authenticate#order'
    end
  end

  # Staff Login system
  get "login", to: "staffs#login"
  post "validate", to: "staffs#validate"
  get "logout", to: "staffs#logout"
  get "dashboard", to: "orders#unsolve"

  resources :details
  resources :orders
  resources :products
  resources :staffs
  resources :departments
  resources :customers
  root "staffs#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :department
  has_many :details
  validates_associated :details
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate
  before_action :set_order, only: [:show, :edit, :update, :destroy, :done]

  def done
    @order.status = false
    render :show, status: "Update", location: @order
  end

  # GET /orders
  # GET /orders.json
  def unsolve
    if session[:staff] == 1
      @orders = Order.where(status: true)
    else
      @department = Staff.find_by(id: session[:staff]).department
      @orders = Order.where(status: true, department: @department)
    end
  end

  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @details = Detail.where(order_id: @order.id)
    # @staff_dep = Staff.find(session[:staff]).department if session[:staff] != 1
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.status = true
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :delivery, :gate, :remark, :payment, :status, :department_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :delivery %>
    <%= f.text_field :delivery %>
  </div>

  <div class="field">
    <%= f.label :gate %>
    <%= f.text_field :gate %>
  </div>

  <div class="field">
    <%= f.label :remark %>
    <%= f.text_field :remark %>
  </div>

  <div class="field">
    <%= f.label :payment %>
    <%= f.text_field :payment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
        <p id="notice"><%= flash[:notice] %></p>
  </div>
<% end %>

<h1>Orders</h1>

<table class="dt table table-striped table-bordered">
  <thead>
    <tr>
      <th>Vocher</th>
      <th>Customer</th>
      <th>Delivery</th>
      <th>Gate</th>
      <th>Remark</th>
      <th>Payment</th>
      <th>Department</th>
      <th>Status</th>
      <th>Date</th>
      <th>Time</th>
      <!-- <th>Download</th> -->
      <% if session[:staff] == 1 %><th>ADMIN</th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "V000#{order.id}", order %></td>
        <td>
          <% if session[:staff] == 1 %>
            <%= link_to order.customer.name, customer_path(order.customer) %>
          <% else %>
            <%= order.customer.name %>
          <% end %>
        </td>
        <td><%= order.delivery %></td>
        <td><%= order.gate %></td>
        <td><%= order.remark %></td>
        <td><%= order.payment %></td>
        <td><%= order.department.name %></td>
        <td><%= order.status %></td>
        <td><%= order.created_at.strftime("%e-%-m-%Y") %></td>
        <td><%= order.created_at.strftime("%H:%M:%S") %></td>
        <!-- <td>
          <%= link_to ':EXCEL', order_download_path(id: order.id, format: 'csv') %>
        </td> -->
        <% if session[:staff] == 1 %>
          <td>
            <%= link_to 'Edit', edit_order_path(order) %>
            <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-bordered table-condensed">
  <tbody>
    <tr>
      <td><strong>Customer:</strong></td>
      <td><%= @order.customer.name %></td>
    </tr>
    <tr>
      <td><strong>Delivery:</strong></td>
      <td><%= @order.delivery %></td>
    </tr>
    <tr>
      <td><strong>Gate:</strong></td>
      <td><%= @order.gate %></td>
    </tr>
    <tr>
      <td><strong>Remark:</strong></td>
      <td><%= @order.remark %></td>
    </tr>
    <tr>
      <td><strong>Payment:</strong></td>
      <td><%= @order.payment %></td>
    </tr>
    <!--
      <td><% link_to 'Edit', edit_order_path(@order) %></td>
      <td></td>
    </tr>  -->
  </tbody>
</table>

<table class="table table-bordered">
  <thead>
    <tr>
      <td>Product</td>
      <td>Qty</td>
      <!-- <td>Price</td>
      <td>Remark</td> -->
      <td>Remove</td>
    </tr>
  </thead>
  <tbody>
    <% match = true if @order.department == Staff.find(session[:staff]).department && @order.status == true %>
    <% @details.each do |d| %>
      <tr>
        <td><%= d.name %></td>
        <td>
          <% if session[:staff] != 1 && match %>
            <input type="text" name="" value="<%= d.qty %>">
          <% else %>
            <%= d.qty  %>
          <% end %>
        </td>
        <!-- <td><%= d.price %></td>
        <td><%= d.remark %></td> -->
        <td>
          <%= link_to "Destroy", detail_path(d,order: @order), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if match %>
  <%= form_for(@order) do |f| %>
    <div class="actions">
      <%= f.hidden_field :status, value: false %>
      <%= f.submit "Fulfill order", class: 'btn btn-primary',data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
  <br>
<% end %>
<%= link_to 'Print', "#", class: 'btn btn-warning', onclick: 'window.print()' %>
<hr>
<%= link_to 'Back', orders_path %>

app/views/orders/unsolve.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
        <p id="notice"><%= flash[:notice] %></p>
  </div>
<% end %>

<h1>Orders</h1>

<table class="dt table table-striped table-bordered">
  <thead>
    <tr>
      <th>Vocher</th>
      <th>Customer</th>
      <th>Delivery</th>
      <th>Gate</th>
      <th>Remark</th>
      <th>Payment</th>
      <th>Total</th>
      <th>Department</th>
      <th>Date</th>
      <th>Time</th>
      <% unless session[:staff] == 1 %><th></th><% end %>
    </tr>
  </thead>

  <tbody>

    <% if @orders %>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to "V000#{order.id}", order %></td>
          <td>
            <% if session[:staff] == 1 %>
              <%= link_to order.customer.name, customer_path(order.customer) %>
            <% else %>
              <%= order.customer.name %>
            <% end %>
          </td>
          <td><%= order.delivery %></td>
          <td><%= order.gate %></td>
          <td><%= order.remark %></td>
          <td><%= order.payment %></td>
          <td><%= order.total %></td>
          <td><%= order.department.name %></td>
          <td><%= order.created_at.to_date %></td>
          <td><%= order.created_at.strftime("%H:%M:%S") %></td>
          <% unless session[:staff] == 1 %>
          <td>
            <%= link_to 'Done', order, data: { confirm: 'Are you sure?' } %></td>
          </td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="9">No incoming order yet</td>
      </tr>
    <% end %>
  </tbody>
</table>