config/routes.rb
Rails.application.routes.draw do

  # Orders
  get 'order_done', to: 'orders#done'
  get 'order_download', to: 'orders#order_download'

  # API
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'login', to: "authenticate#login"
      get 'orders', to: 'authenticate#orders'
      post 'orders', to: 'authenticate#order'
    end
  end

  # Staff Login system
  get "login", to: "staffs#login"
  post "validate", to: "staffs#validate"
  get "logout", to: "staffs#logout"
  get "dashboard", to: "orders#unsolve"

  resources :details
  resources :orders
  resources :products
  resources :staffs
  resources :departments
  resources :customers
  root "staffs#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DawAye</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Daw Aye", root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if session[:staff] && session[:staff] != nil %>
              <%
                if session[:staff] == 1
                  order_status = Order.where(status: true)
                else
                  order_status = Order.where(status: true, department: Staff.find_by(id: session[:staff]).department)
                end
               %>
              <li><%= link_to "New Orders#{'(' + order_status.count.to_s + ')' if order_status}", dashboard_path %></li>
              <li><%= link_to "Logout", logout_path %></li>
              <li><a href="#">Help</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <% if session[:staff] %>
              <li class="page-header"><h3 style="padding-left:20px;color:#999;"><%= session[:staff_username] if session[:staff] %></h3></li>
              <% if session[:staff] == 1  %>
                <li><%= link_to "Customers", customers_path %></li>
                <li><%= link_to "Staffs", staffs_path %></li>
                <li><%= link_to "Departments", departments_path %></li>
                <li><%= link_to "Products", products_path %></li>
              <% end  %>
              <li><%= link_to "Orders", orders_path %></li>
            <% end  %>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>